### ISSUE TITLE
Learn GitHub interface and read the docs

### ISSUE THREAD

**Issue by iradche** [IPMITMO/github-community-research#2]

**Comment by iradche** [comment]
- Code School: https://try.github.io/levels/1/challenges/1
- A specially curated list of our favorite resources for learning more about Git and GitHub. https://github.com/github
- GitHub Services repos. https://services.github.com/classnotes/
- Git Cheat Sheet. https://services.github.com/kit/downloads/github-git-cheat-sheet.pdf

**Comment by annkupriyanova** [comment]
- Git simple guide: http://rogerdudler.github.io/git-guide/
- Visual Git Reference: http://marklodato.github.io/visual-git-guide/index-en.html
